cargo-features = ["edition"]

[package]
name = "epilogue"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]
edition = "2018"

[dependencies]
nom = "4.0"
prettytable-rs = "0.7"
rustyline = "1.0"
